// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Book Now"
          text="Ready to experience profound relaxation? Contact us for bookings."
          primaryButton={{
            text: "Call 0476 02 04 37",
            href: "tel:0476020437",
          }}
          secondaryButton={{
            text: "Visit Website",
            href: "https://suniethaimassage.be",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
