// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "gallery" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function GallerySection(): React.JSX.Element {
  return (
    <div id="gallery" data-section="gallery">
        <SectionErrorBoundary name="gallery">
              <FeaturesArrowCards
          tag="Studio"
          title="Our Ambiance"
          description="Step into a sanctuary of peace."
          items={[
            {
              title: "Reception",
              tags: [
                "Zen",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/spa-relaxation-room_23-2151945668.jpg",
            },
            {
              title: "Treatment Room",
              tags: [
                "Luxury",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-cup-tea-decor-items-light-wooden-table-top-view_169016-3980.jpg",
            },
            {
              title: "Details",
              tags: [
                "Decor",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-spa-frame-with-copy-space-concept_23-2148290971.jpg",
            },
            {
              title: "Sanctuary",
              tags: [
                "Calm",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/autumn-decoration-with-herbs-spoon_23-2147709574.jpg",
            },
            {
              title: "Ambiance",
              tags: [
                "Warm",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/harmonic-decoration_23-2147621411.jpg",
            },
            {
              title: "Reflection",
              tags: [
                "Peace",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-organic-soap-bars_23-2150533278.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
