// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboard
          title="Authentic Thai Massage, Rooted in Tradition"
          description="Experience serene, personalized Thai wellness in the heart of Kalmthout. Restorative treatments tailored to your comfort."
          primaryButton={{
            text: "Book Now",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Services",
            href: "#services",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/buddha-figurine-still-life_23-2150514574.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
