/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { MapPin, Clock, Phone } from 'lucide-react';
import type { LucideIcon } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { resolveIcon } from "@/utils/resolve-icon";

const metrics = [
  {
    icon: MapPin,
    title: "Address",
    value: "Thillostraat 33"
  },
  {
    icon: Clock,
    title: "Open Today",
    value: "09:00 - 21:00"
  },
  {
    icon: Phone,
    title: "Call",
    value: "0476 02 04 37"
  }
];

type Metric = {
  icon: string | LucideIcon;
  title: string;
  value: string;
};

const LocationInline = () => (
  <section aria-label="Metrics section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Visit Us"}</p>
        </div>

        <TextAnimation
          text={"Location & Hours"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Thillostraat 33, 2920 Kalmthout, Belgium. Today: Open until 21:00."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up">
        <GridOrCarousel>
          {metrics.map((metric) => {
            const IconComponent = resolveIcon(metric.icon);
            return (
              <div key={metric.value} className="flex flex-col items-center justify-center gap-3 xl:gap-3.5 2xl:gap-4 p-6 xl:p-7 2xl:p-8 min-h-70 xl:min-h-80 2xl:min-h-90 h-full card rounded">
                <div className="flex items-center justify-center gap-2 min-w-0">
                  <div className="flex items-center justify-center shrink-0 size-8 primary-button rounded">
                    <IconComponent className="h-2/5 w-2/5 text-primary-cta-text" strokeWidth={1.5} />
                  </div>
                  <span className="text-xl truncate min-w-0">{metric.title}</span>
                </div>
                <span className="text-9xl md:text-8xl font-semibold leading-none truncate">{metric.value}</span>
              </div>
            );
          })}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function LocationSection() {
  return (
    <div data-webild-section="location" data-section="location" id="location">
      <LocationInline />
    </div>
  );
}
