// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesImageBento
          tag="Treatments"
          title="Our Wellness Rituals"
          description="Expertly crafted Thai massage treatments designed to restore balance and relieve tension."
          items={[
            {
              title: "Traditional Thai",
              description: "Classic technique for full-body restoration.",
              imageSrc: "http://img.b2bpic.net/free-photo/shoulder-opening-back-massage-smooth-motion-balance_169016-69007.jpg",
            },
            {
              title: "Deep Tissue",
              description: "Targeted relief for persistent pain points.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-receiving-relaxing-massage-spa_23-2148176890.jpg",
            },
            {
              title: "Relaxation",
              description: "Gentle, calming session to quiet the mind.",
              imageSrc: "http://img.b2bpic.net/free-photo/spa-concept-top-view-beautiful-spa-products-with-place-text-essential-oils-with-beautiful-flowers-towels-spa-salt-hand-made-soap_1220-1193.jpg",
            },
            {
              title: "Foot Reflexology",
              description: "Revitalizing pressure on key foot points.",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-foot-massage-with-oil-heel-toe-relaxation_169016-69500.jpg",
            },
            {
              title: "Herbal Compress",
              description: "Warm, aromatic healing herbs treatment.",
              imageSrc: "http://img.b2bpic.net/free-photo/spa-wellness-setting-with-flowers-towels-bright-composition-brown-table-with-tropical-flowers-dayspa-nature-products-with-coconut_169016-1643.jpg",
            },
            {
              title: "Back & Shoulder",
              description: "Specialized attention for desk fatigue.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiley-doctor-giving-ct-scan-patient_23-2149341503.jpg",
            },
            {
              title: "Custom Session",
              description: "Personalized therapy for specific needs.",
              imageSrc: "http://img.b2bpic.net/free-photo/photorealistic-wooden-house-interior-with-timber-decor-furnishings_23-2151263507.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
