// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Reviews"
          title="Honored by Our Clients"
          description="5.0 rating based on 149 Google reviews."
          testimonials={[
            {
              name: "Els M.",
              role: "Visitor",
              company: "Google Review",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-happy-woman-having-back-massage-while-spending-day-beauty-spa_637285-7424.jpg",
            },
            {
              name: "Jan V.",
              role: "Regular",
              company: "Google Review",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/getting-ready-spa_1098-19902.jpg",
            },
            {
              name: "Sarah K.",
              role: "Client",
              company: "Google Review",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-stylish-woman-posing-fashionable-outfit_23-2149021814.jpg",
            },
            {
              name: "Peter D.",
              role: "Visitor",
              company: "Google Review",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/morning-portrait-pretty-woman-relaxing-bed-after-shower-wearing-bath-robe-towel-her-head-drinking-tasty-tea_291049-2695.jpg",
            },
            {
              name: "Lieve D.",
              role: "Regular",
              company: "Google Review",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-women-selfcare-treatments_23-2149168538.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
